# Generated by Django 4.0.1 on 2022-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Enter your full name here')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email here')),
                ('text', models.TextField(verbose_name='Enter your message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
