# Generated by Django 4.0.1 on 2022-01-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_id_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Private (with a uuid to access)'), (1, 'Public (everyone can access)')], default=1),
        ),
        migrations.CreateModel(
            name='FavoritePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
    ]
