# Generated by Django 4.0.1 on 2022-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_status_favoritepoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='anonymous_voters',
            field=models.ManyToManyField(to='polls.AnonymousVoter'),
        ),
    ]
