# Generated by Django 4.0.1 on 2022-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_anonymousvoter_poll_anonymous_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
