# Generated by Django 4.0.1 on 2022-01-25 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_option_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='authenticated_voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
