# Generated by Django 4.0.1 on 2022-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_poll_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='public_key',
            field=models.CharField(default='452aDM@W!z&tF{Zs', editable=False, max_length=16),
        ),
    ]
