# Generated by Django 4.0.1 on 2022-01-26 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_poll_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='anonymous_voters',
            field=models.ManyToManyField(blank=True, to='polls.AnonymousVoter'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='authenticated_voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='public_key',
            field=models.CharField(default='jhI0J*4pvgiz3Ls2', editable=False, max_length=16),
        ),
    ]
