# Generated by Django 4.0.1 on 2022-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_poll_anonymous_voters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='public_key',
            field=models.CharField(default='\\*x}WHMGrw6zD7Ty', editable=False, max_length=16, null=True),
        ),
    ]
