# Generated by Django 4.0.1 on 2022-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_poll_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='public_key',
        ),
        migrations.AddField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='sklLrDtuT12(fa7H', editable=False, max_length=16, null=True),
        ),
    ]
