# Generated by Django 4.0.1 on 2022-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_poll_public_key_poll_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='H{s1KI*W4L?/EtFO', editable=False, max_length=16, null=True),
        ),
    ]
