# Generated by Django 4.0.1 on 2022-01-26 15:40

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_poll_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default=polls.models.generate_private_key, editable=False, max_length=16, null=True),
        ),
    ]
