# Generated by Django 4.0.1 on 2022-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_poll_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_count_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_count_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_count_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='option_count_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='U/Z4VEDtASK7I\\vy', editable=False, max_length=16, null=True),
        ),
    ]
