# Generated by Django 4.0.1 on 2022-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_poll_option_1_poll_option_2_poll_option_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='0zokSwrX@lt(REbT', editable=False, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
