# Generated by Django 4.0.1 on 2022-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_poll_option_count_1_alter_poll_option_count_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='v*G{fi^nJVX0gueQ', editable=False, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='FavoritePoll',
        ),
    ]
