# Generated by Django 4.0.1 on 2022-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_poll_private_key_delete_favoritepoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='$s!1kv5Lu/}nP{Bg', editable=False, max_length=16, null=True),
        ),
    ]
