# Generated by Django 4.0.1 on 2022-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_poll_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_key',
            field=models.CharField(default='36Svr}JoClqTePF5', editable=False, max_length=16, null=True),
        ),
    ]
